### ISSUE TITLE
no main file to run?

### ISSUE THREAD

**Issue by harshraj32** [iRxyzzz/nn-emd#1]
which file should i run first

**Comment by iRxyzzz** [comment]
Hi there,  all test code is at `experiment/exp.py`, you can use `pytest` to run each functions. Also, you can check the script in the `script` folder.

**Comment by irxyzzz** [comment]
> which file should i run first

All test code is at experiment/exp.py, you can use pytest to run each functions. Also, you can check the script in the script folder.
